### ISSUE TITLE
Must use import to load ES Module

### ISSUE THREAD

**Issue by stfsy** [lagden/postcss-inline-base64#13]
Hi @lagden, wanted to check whether this breaking changes was intentional as it's not reflected in the changelog or readme.

I'm using postcss-inline-base64 as a part of my build pipeline. With the newest version the build fails with the following error:

```
Error [ERR_REQUIRE_ESM]: Must use import to load ES Module: C:\workspace\...\node_modules\postcss-inline-base64\src\index.js
require() of ES modules is not supported.
require() of C:\workspace\...\node_modules\postcss-inline-base64\src\index.js from C:\workspace\...\blauspecht-frontend\postcss.config.js is an ES module file as it is a .js file whose nearest parent package.json contains "type": "module" which defines all .js files in that package scope as ES modules.
Instead rename index.js to end in .cjs, change the requiring code to use import(), 
or remove "type": "module" from C:\workspace\...\node_modules\postcss-inline-base64\package.json.
```

Configuration
```js
module.exports = {
    plugins: [
        require('postcss-import'),
        require('tailwindcss'),
        require('postcss-inline-base64'),
        require('autoprefixer'),
        require('cssnano'),
        require('postcss-nested')
    ]
}
```

**Comment by lagden** [comment]
Hi @stfsy 

The diff between 7.x and 6.x is `type: module`, the code still is the same.
Keep using the prior release `6.2.1` in your project.

```json
{
  "devDependencies": {
    "postcss-inline-base64": "6.2.1"
  }
}
```

or use next release `7.1.0` and setup something like this:

```js
module.exports = {
    plugins: [
        require('postcss-inline-base64/dist/plugin'),
        //...
    ]
}
```

**Comment by lagden** [comment]
feel free to reopen if necessary.

**Comment by stfsy** [comment]
@lagden thank you

**Comment by dopry** [comment]
```
        require('postcss-inline-base64/dist/plugin'),
```

doesn't seem to work for 7.x since, I get the following

```
Error [ERR_REQUIRE_ESM]: Must use import to load ES Module: C:\...\node_modules\postcss-inline-base64\dist\plugin.js
require() of ES modules is not supported.
require() of C:\...\node_modules\postcss-inline-base64\dist\plugin.js from C:\...\postcss.config.cjs is an ES module file as it is a .js file whose nearest parent package.json contains "type": "module" which defines all .js files in that package scope as ES modules.
Instead rename plugin.js to end in .cjs, change the requiring code to use import(), or remove "type": "module" from C:\...\node_modules\postcss-inline-base64\package.json.
```

**Comment by lagden** [comment]
Hey @dopry

Update to 7.2.1
I fixed it and put the example at README.md file

```js
require('postcss-inline-base64/dist/plugin.cjs')
```

try again and give a feedback.

https://unpkg.com/postcss-inline-base64@7.2.1/dist/plugin.cjs

**Comment by mpontus** [comment]
@lagden 

Thank you for your suggestion. However, the instructions do not seem sufficient and still results in an error when postcss is used in webpack build process:

```
 ERROR #98123  WEBPACK

Generating JavaScript bundles failed

Module build failed (from ./node_modules/postcss-loader/dist/cjs.js):
Error [ERR_REQUIRE_ESM]: require() of ES Module
/home/mpontus/projects/kf-website/node_modules/postcss-inline-base64/node_modules/got/dist/source/index.js from
/home/mpontus/projects/kf-website/node_modules/postcss-inline-base64/dist/plugin.cjs not supported.
Instead change the require of index.js in /home/mpontus/projects/kf-website/node_modules/postcss-inline-base64/dist/plugin.cjs to a
dynamic import() which is available in all CommonJS modules.
    at Object.<anonymous> (/home/mpontus/projects/kf-website/node_modules/postcss-inline-base64/dist/plugin.cjs:1:723)
    at Object.<anonymous> (/home/mpontus/projects/kf-website/postcss.config.js:3:13)
    at module.exports (/home/mpontus/projects/kf-website/node_modules/import-fresh/index.js:32:59)
    at loadJs (/home/mpontus/projects/kf-website/node_modules/postcss-loader/node_modules/cosmiconfig/dist/loaders.js:16:18)
    at Explorer.loadFileContent
(/home/mpontus/projects/kf-website/node_modules/postcss-loader/node_modules/cosmiconfig/dist/Explorer.js:84:32)
    at Explorer.createCosmiconfigResult
(/home/mpontus/projects/kf-website/node_modules/postcss-loader/node_modules/cosmiconfig/dist/Explorer.js:89:36)
    at Explorer.loadSearchPlace
(/home/mpontus/projects/kf-website/node_modules/postcss-loader/node_modules/cosmiconfig/dist/Explorer.js:70:31)
    at async Explorer.searchDirectory
(/home/mpontus/projects/kf-website/node_modules/postcss-loader/node_modules/cosmiconfig/dist/Explorer.js:55:27)
    at async run (/home/mpontus/projects/kf-website/node_modules/postcss-loader/node_modules/cosmiconfig/dist/Explorer.js:35:22)
    at async cacheWrapper
(/home/mpontus/projects/kf-website/node_modules/postcss-loader/node_modules/cosmiconfig/dist/cacheWrapper.js:16:18)
    at async cacheWrapper
(/home/mpontus/projects/kf-website/node_modules/postcss-loader/node_modules/cosmiconfig/dist/cacheWrapper.js:16:18)
    at async Explorer.search
(/home/mpontus/projects/kf-website/node_modules/postcss-loader/node_modules/cosmiconfig/dist/Explorer.js:27:20)
    at async loadConfig (/home/mpontus/projects/kf-website/node_modules/postcss-loader/dist/utils.js:66:16)
    at async Object.loader (/home/mpontus/projects/kf-website/node_modules/postcss-loader/dist/index.js:54:22)

File: src/global.css
````

Here's what `postcss.config.js` looks like:

```js
module.exports = {
  plugins: [require('postcss-inline-base64/dist/plugin.cjs')()],
}
```

**Comment by lagden** [comment]
oh my!! my bad!
I set the lib `got` as external.

---

It has been fixed and I ran a local test to confirm.

```js
const postcss = require('postcss')
const base64 = require('postcss-inline-base64')

const input = `body {
  background: #ffffff url('b64---https://www.google.com/images/branding/googlelogo/2x/googlelogo_light_color_92x30dp.png---') no-repeat right top;
}`

postcss([base64()])
	.process(input, {from: undefined})
	.then(result => {
		console.log('result --->', result.css)
	})


```

```
result ---> body {
  background: #ffffff url('data:image/png;charset=utf-8;base64,iVBORw0KG...rkJggg==') no-repeat right top;
}
```

and added `exports` to auto detect `module` or `commonjs` 

https://github.com/lagden/postcss-inline-base64/blob/master/package.json#L22-L27

---

postcss-inline-base64@7.2.2

**Comment by mpontus** [comment]
@lagden Yep! That fixed the issue. Thank you for addressing it so quickly

**Comment by BorisKourt** [comment]
Hey, I have updated to `7.2.2` from `6.2.1` and I have:

```
Error [ERR_PACKAGE_PATH_NOT_EXPORTED]: Package subpath './dist/plugin.cjs' is not defined by "exports" in /Users/<snip>/node_modules/postcss-inline-base64/package.json
```
My `postcss.config.js` is:

```js
module.exports = {
  plugins: [
    require('postcss-inline-base64/dist/plugin.cjs'),
    require('postcss-import'),
    require('postcss-inline-svg'),
    require('autoprefixer'),
    require('cssnano')
  ]
};
```

`npm ls` is:

```
├── autoprefixer@10.4.5
├── cssnano@5.1.7
├── postcss-import@14.1.0
├── postcss-inline-base64@7.2.2
└── postcss-inline-svg@5.0.0
```

Did I make a config mistake somewhere? Thanks!

**Comment by lagden** [comment]
@BorisKourt 

Just use: `require('postcss-inline-base64')`.
And the `version 7` is only compatible with `postcss 8`
